### ISSUE TITLE
Accessory not updating in Homekit

### ISSUE THREAD

**Issue by eighthree** [marcjordant/homebridge-hue-temperature#3]
Just finished setting up and added the accessories within Homekit but the modules won't update. Switches etc, report & work fine.

I've tried:
* Reset persist folder/ remove homebridge & re-add on homekit.
* Check logs for start up or config issues (no errors).
* Double checking credentials and ID within CLIP API Debugger to make sure I'm using the right ID

Running on a vanilla raspbian with homebridge + homebridge plugins: homebridge server, cmdSwitch2, mqtt & Wemo

**Comment by marcjordant** [comment]
Can you post your config file and the log of HomeKit please ?

**Comment by marcjordant** [comment]
In absence of more information I'll close the issue.
Feel free to reopen it with more information.
